-- Baseline schema for ShopCore (public schema only)
-- Contains the public schema objects required to initialize the database.

begin;

set search_path = public;

-- ========== Extensions ==========

create extension if not exists "pgcrypto" with schema public;

-- ========== Domains ==========

create domain public."d_money" as numeric(12,2) default 0 not null;
alter domain public."d_money" add constraint "d_money_check" CHECK (VALUE >= 0::numeric);
alter domain public."d_money" add constraint "d_money_not_null" NOT NULL;

-- ========== Sequences ==========

create sequence public."auth_users_user_id_seq" increment by 1 minvalue 1 maxvalue 2147483647 start with 1 cache 1 no cycle;
create sequence public."seq_categories_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public."seq_customers_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public."seq_deliveries_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public."seq_order_items_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public."seq_orders_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public."seq_payments_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public."seq_products_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public."seq_shipment_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public."seq_suppliers_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public."seq_supply_item_id" increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;

-- ========== Tables ==========

create table public."auth_users" (
  "user_id" integer generated by default as identity not null,
  "role_name" character varying(20) default 'user'::character varying not null,
  "customer_id" integer,
  "email" character varying(255) not null,
  "password_hash" character varying(255) not null,
  "full_name" character varying(255),
  "is_active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table public."categories" (
  "category_id" integer not null,
  "category_name" character varying(100) not null,
  "description" character varying(255)
);

create table public."customers" (
  "customer_id" integer not null,
  "full_name" character varying(100) not null,
  "phone_number" character varying(20),
  "email" character varying(100),
  "address" character varying(255)
);

create table public."deliveries" (
  "delivery_id" integer not null,
  "supplier_id" integer not null,
  "delivery_date" date not null,
  "invoice_number" character varying(50) not null
);

create table public."order_items" (
  "order_item_id" integer not null,
  "order_id" integer not null,
  "product_id" integer not null,
  "quantity" integer not null,
  "sale_price" d_money not null,
  "discount" numeric(5,2) default 0 not null,
  "line_amount" d_money not null
);

create table public."orders" (
  "order_id" integer not null,
  "customer_id" integer not null,
  "order_date" date not null,
  "status" character varying(30) not null,
  "total_amount" d_money not null,
  "payment_method" character varying(30)
);

create table public."payments" (
  "payment_id" integer not null,
  "order_id" integer not null,
  "payment_date" date not null,
  "amount" d_money not null,
  "payment_method" character varying(30) not null,
  "status" character varying(30) not null
);

create table public."products" (
  "product_id" integer not null,
  "category_id" integer not null,
  "name" character varying(100) not null,
  "price" d_money not null,
  "stock_quantity" integer not null,
  "discount" numeric(5,2) default 0 not null,
  "description" character varying(500),
  "image_url" character varying(500),
  "image_public_id" character varying(255)
);

create table public."shipment" (
  "shipment_id" integer not null,
  "order_id" integer not null,
  "shipping_service" character varying(100) not null,
  "tracking_number" character varying(50),
  "shipping_address" character varying(255) not null,
  "shipping_status" character varying(30) not null
);

create table public."suppliers" (
  "supplier_id" integer not null,
  "name" character varying(100) not null,
  "phone_number" character varying(20),
  "email" character varying(100)
);

create table public."supply_item" (
  "supply_item_id" integer not null,
  "delivery_id" integer not null,
  "product_id" integer not null,
  "quantity" integer not null,
  "supply_price" d_money not null
);

create table public."user_roles" (
  "role_name" character varying(20) not null,
  "description" character varying(255),
  "created_at" timestamp with time zone default now() not null
);

create table public."user_sessions" (
  "session_id" uuid default gen_random_uuid() not null,
  "user_id" integer not null,
  "session_token_hash" character varying(255) not null,
  "created_at" timestamp with time zone default now() not null,
  "expires_at" timestamp with time zone not null,
  "last_used_at" timestamp with time zone,
  "revoked_at" timestamp with time zone,
  "user_agent" text,
  "ip_address" inet
);

-- ========== Constraints ==========

alter table public."auth_users" add constraint "auth_users_pkey" PRIMARY KEY (user_id);
alter table public."categories" add constraint "pk_categories" PRIMARY KEY (category_id);
alter table public."customers" add constraint "pk_customers" PRIMARY KEY (customer_id);
alter table public."deliveries" add constraint "pk_deliveries" PRIMARY KEY (delivery_id);
alter table public."order_items" add constraint "pk_order_items" PRIMARY KEY (order_item_id);
alter table public."orders" add constraint "pk_orders" PRIMARY KEY (order_id);
alter table public."payments" add constraint "pk_payments" PRIMARY KEY (payment_id);
alter table public."products" add constraint "pk_products" PRIMARY KEY (product_id);
alter table public."shipment" add constraint "pk_shipment" PRIMARY KEY (shipment_id);
alter table public."suppliers" add constraint "pk_suppliers" PRIMARY KEY (supplier_id);
alter table public."supply_item" add constraint "pk_supply_item" PRIMARY KEY (supply_item_id);
alter table public."user_roles" add constraint "user_roles_pkey" PRIMARY KEY (role_name);
alter table public."user_sessions" add constraint "user_sessions_pkey" PRIMARY KEY (session_id);
alter table public."auth_users" add constraint "auth_users_customer_id_key" UNIQUE (customer_id);
alter table public."auth_users" add constraint "uq_auth_users_email" UNIQUE (email);
alter table public."payments" add constraint "uq_payments_order" UNIQUE (order_id);
alter table public."shipment" add constraint "uq_shipment_order" UNIQUE (order_id);
alter table public."user_sessions" add constraint "uq_user_sessions_token_hash" UNIQUE (session_token_hash);
alter table public."deliveries" add constraint "chk_deliveries_delivery_date_not_future" CHECK (delivery_date <= CURRENT_DATE);
alter table public."order_items" add constraint "chk_order_items_discount" CHECK (discount >= 0::numeric AND discount <= 100::numeric);
alter table public."order_items" add constraint "chk_order_items_line_amount" CHECK (line_amount::numeric >= 0::numeric);
alter table public."order_items" add constraint "chk_order_items_quantity" CHECK (quantity > 0);
alter table public."order_items" add constraint "chk_order_items_sale_price" CHECK (sale_price::numeric > 0::numeric);
alter table public."orders" add constraint "chk_orders_order_date_not_future" CHECK (order_date <= CURRENT_DATE);
alter table public."orders" add constraint "chk_orders_payment_method" CHECK (payment_method IS NULL OR (payment_method::text = ANY (ARRAY['card'::character varying, 'iban'::character varying, 'cash_on_delivery'::character varying]::text[])));
alter table public."orders" add constraint "chk_orders_total_amount" CHECK (total_amount::numeric >= 0::numeric);
alter table public."payments" add constraint "chk_payments_amount" CHECK (amount::numeric > 0::numeric);
alter table public."payments" add constraint "chk_payments_payment_date_not_future" CHECK (payment_date <= CURRENT_DATE);
alter table public."products" add constraint "chk_products_discount" CHECK (discount >= 0::numeric AND discount <= 100::numeric);
alter table public."products" add constraint "chk_products_price" CHECK (price::numeric > 0::numeric);
alter table public."products" add constraint "chk_products_stock_quantity" CHECK (stock_quantity >= 0);
alter table public."supply_item" add constraint "chk_supply_item_quantity" CHECK (quantity > 0);
alter table public."supply_item" add constraint "chk_supply_item_supply_price" CHECK (supply_price::numeric > 0::numeric);
alter table public."user_roles" add constraint "chk_user_roles_name" CHECK (role_name::text = ANY (ARRAY['admin'::character varying, 'user'::character varying]::text[]));
alter table public."user_sessions" add constraint "chk_user_sessions_expires_after_created" CHECK (expires_at > created_at);
alter table public."auth_users" add constraint "fk_auth_users_customer" FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON UPDATE CASCADE ON DELETE SET NULL;
alter table public."auth_users" add constraint "fk_auth_users_role" FOREIGN KEY (role_name) REFERENCES user_roles(role_name) ON UPDATE CASCADE ON DELETE RESTRICT;
alter table public."deliveries" add constraint "fk_deliveries_suppliers" FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id);
alter table public."order_items" add constraint "fk_order_items_orders" FOREIGN KEY (order_id) REFERENCES orders(order_id);
alter table public."order_items" add constraint "fk_order_items_products" FOREIGN KEY (product_id) REFERENCES products(product_id);
alter table public."orders" add constraint "fk_orders_customers" FOREIGN KEY (customer_id) REFERENCES customers(customer_id);
alter table public."payments" add constraint "fk_payments_orders" FOREIGN KEY (order_id) REFERENCES orders(order_id);
alter table public."products" add constraint "fk_products_categories" FOREIGN KEY (category_id) REFERENCES categories(category_id);
alter table public."shipment" add constraint "fk_shipment_orders" FOREIGN KEY (order_id) REFERENCES orders(order_id);
alter table public."supply_item" add constraint "fk_supply_item_deliveries" FOREIGN KEY (delivery_id) REFERENCES deliveries(delivery_id);
alter table public."supply_item" add constraint "fk_supply_item_products" FOREIGN KEY (product_id) REFERENCES products(product_id);
alter table public."user_sessions" add constraint "fk_user_sessions_user" FOREIGN KEY (user_id) REFERENCES auth_users(user_id) ON UPDATE CASCADE ON DELETE CASCADE;

-- ========== Indexes ==========

CREATE INDEX idx_auth_users_role_name ON public.auth_users USING btree (role_name);
CREATE INDEX idx_user_sessions_active ON public.user_sessions USING btree (user_id, expires_at) WHERE (revoked_at IS NULL);
CREATE INDEX idx_user_sessions_expires_at ON public.user_sessions USING btree (expires_at);
CREATE INDEX idx_user_sessions_user_id ON public.user_sessions USING btree (user_id);

-- ========== Views ==========

create or replace view public."v_available_products" as
 SELECT product_id,
    category_id,
    name,
    price,
    stock_quantity,
    discount,
   description,
   image_url,
   image_public_id
  FROM public.products
  WHERE stock_quantity > 0;

create or replace view public."v_order_details" as
 SELECT oi.order_item_id,
    o.order_id,
    o.order_date,
    o.status AS order_status,
    o.total_amount,
    c.customer_id,
    c.full_name AS customer_name,
    c.phone_number,
    c.email,
    p.product_id,
    p.name AS product_name,
    oi.quantity,
    oi.sale_price,
    oi.discount AS item_discount,
    oi.line_amount,
    pay.payment_date,
    pay.amount AS payment_amount,
    pay.payment_method,
    pay.status AS payment_status,
    sh.shipping_service,
    sh.tracking_number,
    sh.shipping_address,
    sh.shipping_status
   FROM order_items oi
     JOIN orders o ON oi.order_id = o.order_id
     JOIN customers c ON o.customer_id = c.customer_id
     JOIN products p ON oi.product_id = p.product_id
     LEFT JOIN payments pay ON o.order_id = pay.order_id
     LEFT JOIN shipment sh ON o.order_id = sh.order_id;

-- ========== Functions And Procedures ==========

CREATE OR REPLACE FUNCTION public.fn_customer_orders(p_customer_id integer)
 RETURNS TABLE(order_id integer, order_date date, order_status character varying, total_amount numeric, payment_status character varying, shipping_status character varying)
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public', 'pg_temp'
AS $function$
begin
  return query
  select
    o.order_id,
    o.order_date,
    o.status as order_status,
    o.total_amount::numeric(12, 2),
    coalesce(pay.status, 'No payment') as payment_status,
    coalesce(sh.shipping_status, 'No shipment') as shipping_status
  from public.orders as o
  left join public.payments as pay
    on pay.order_id = o.order_id
  left join public.shipment as sh
    on sh.order_id = o.order_id
  where o.customer_id = p_customer_id
  order by o.order_date, o.order_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_categories_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.category_id IS NULL THEN
        NEW.category_id := nextval('seq_categories_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_customers_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.customer_id IS NULL THEN
        NEW.customer_id := nextval('seq_customers_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_deliveries_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.delivery_id IS NULL THEN
        NEW.delivery_id := nextval('seq_deliveries_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_order_items_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.order_item_id IS NULL THEN
        NEW.order_item_id := nextval('seq_order_items_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_orders_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.order_id IS NULL THEN
        NEW.order_id := nextval('seq_orders_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_payments_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.payment_id IS NULL THEN
        NEW.payment_id := nextval('seq_payments_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_products_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.product_id IS NULL THEN
        NEW.product_id := nextval('seq_products_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_shipment_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.shipment_id IS NULL THEN
        NEW.shipment_id := nextval('seq_shipment_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_suppliers_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.supplier_id IS NULL THEN
        NEW.supplier_id := nextval('seq_suppliers_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_supply_item_id()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.supply_item_id IS NULL THEN
        NEW.supply_item_id := nextval('seq_supply_item_id');
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_sold_products_by_date(p_order_date date)
 RETURNS TABLE(product_id integer, product_name character varying, total_quantity integer, total_amount numeric)
 LANGUAGE sql
 STABLE
AS $function$
  select
    p.product_id,
    p.name as product_name,
    sum(oi.quantity)::integer as total_quantity,
    round(sum(oi.line_amount)::numeric, 2) as total_amount
  from public.orders as o
  inner join public.order_items as oi
    on oi.order_id = o.order_id
  inner join public.products as p
    on p.product_id = oi.product_id
  where o.order_date = p_order_date
  group by
    p.product_id,
    p.name
  order by
    sum(oi.quantity) desc,
    p.name asc;
$function$;

CREATE OR REPLACE FUNCTION public.fn_top_categories_by_period(p_date_from date, p_date_to date)
 RETURNS TABLE(category_id integer, category_name character varying, total_quantity integer, total_amount numeric)
 LANGUAGE plpgsql
 STABLE
AS $function$
begin
  if p_date_from > p_date_to then
    raise exception 'Date from cannot be later than date to';
  end if;

  return query
  select
    c.category_id,
    c.category_name,
    sum(oi.quantity)::integer as total_quantity,
    round(sum(oi.line_amount)::numeric, 2) as total_amount
  from public.categories as c
  inner join public.products as p
    on p.category_id = c.category_id
  inner join public.order_items as oi
    on oi.product_id = p.product_id
  inner join public.orders as o
    on o.order_id = oi.order_id
  where o.order_date between p_date_from and p_date_to
  group by
    c.category_id,
    c.category_name
  order by
    sum(oi.quantity) desc,
    sum(oi.line_amount) desc;
end;
$function$;

CREATE OR REPLACE FUNCTION public.pr_create_order(p_customer_id integer, p_order_date date, p_items jsonb, p_payment_method character varying DEFAULT NULL::character varying)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
  v_order_id integer;
  v_total_amount numeric(12, 2) := 0;
  v_item jsonb;
  v_product_id integer;
  v_quantity integer;
  v_sale_price numeric(12, 2);
  v_discount numeric(5, 2);
  v_stock_quantity integer;
  v_line_amount numeric(12, 2);
begin
  if not exists (
    select 1
    from public.customers
    where customer_id = p_customer_id
  ) then
    raise exception 'Customer with ID % does not exist', p_customer_id;
  end if;

  if p_order_date > current_date then
    raise exception 'Order date cannot be later than current date';
  end if;

  if p_items is null
    or jsonb_typeof(p_items) <> 'array'
    or jsonb_array_length(p_items) = 0 then
    raise exception 'Order must contain at least one item';
  end if;

  if p_payment_method is not null
    and p_payment_method not in ('card', 'iban', 'cash_on_delivery') then
    raise exception 'Payment method must be card, iban, or cash_on_delivery';
  end if;

  insert into public.orders (
    customer_id,
    order_date,
    status,
    total_amount,
    payment_method
  )
  values (
    p_customer_id,
    p_order_date,
    'Created',
    0,
    p_payment_method
  )
  returning order_id into v_order_id;

  for v_item in
    select value
    from jsonb_array_elements(p_items)
  loop
    if not (v_item ? 'product_id') or not (v_item ? 'quantity') then
      raise exception 'Each order item must contain product_id and quantity';
    end if;

    v_product_id := (v_item ->> 'product_id')::integer;
    v_quantity := (v_item ->> 'quantity')::integer;

    if v_quantity <= 0 then
      raise exception 'Order item quantity must be greater than 0';
    end if;

    select
      price,
      discount,
      stock_quantity
    into
      v_sale_price,
      v_discount,
      v_stock_quantity
    from public.products
    where product_id = v_product_id
    for update;

    if not found then
      raise exception 'Product with ID % does not exist', v_product_id;
    end if;

    if v_stock_quantity < v_quantity then
      raise exception 'Not enough stock for product ID %', v_product_id;
    end if;

    v_line_amount := round(
      (v_quantity * v_sale_price * (100 - v_discount) / 100)::numeric,
      2
    );

    insert into public.order_items (
      order_id,
      product_id,
      quantity,
      sale_price,
      discount,
      line_amount
    )
    values (
      v_order_id,
      v_product_id,
      v_quantity,
      v_sale_price,
      v_discount,
      v_line_amount
    );

    update public.products
    set stock_quantity = stock_quantity - v_quantity
    where product_id = v_product_id;

    v_total_amount := v_total_amount + v_line_amount;
  end loop;

  update public.orders
  set total_amount = v_total_amount
  where order_id = v_order_id;

  return v_order_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.pr_create_shipment(p_order_id integer, p_shipping_service character varying, p_tracking_number character varying, p_shipping_address character varying, p_shipping_status character varying)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
  v_shipment_id integer;
begin
  if not exists (
    select 1
    from public.orders
    where order_id = p_order_id
  ) then
    raise exception 'Order with ID % does not exist', p_order_id;
  end if;

  if exists (
    select 1
    from public.shipment
    where order_id = p_order_id
  ) then
    raise exception 'Shipment for order ID % already exists', p_order_id;
  end if;

  insert into public.shipment (
    order_id,
    shipping_service,
    tracking_number,
    shipping_address,
    shipping_status
  )
  values (
    p_order_id,
    p_shipping_service,
    p_tracking_number,
    p_shipping_address,
    p_shipping_status
  )
  returning shipment_id into v_shipment_id;

  return v_shipment_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.pr_register_delivery(p_supplier_id integer, p_delivery_date date, p_invoice_number character varying, p_items jsonb)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
  v_delivery_id integer;
  v_item jsonb;
  v_product_id integer;
  v_quantity integer;
  v_supply_price numeric(12, 2);
begin
  if not exists (
    select 1
    from public.suppliers
    where supplier_id = p_supplier_id
  ) then
    raise exception 'Supplier with ID % does not exist', p_supplier_id;
  end if;

  if p_delivery_date > current_date then
    raise exception 'Delivery date cannot be later than current date';
  end if;

  if p_items is null
    or jsonb_typeof(p_items) <> 'array'
    or jsonb_array_length(p_items) = 0 then
    raise exception 'Delivery must contain at least one item';
  end if;

  insert into public.deliveries (
    supplier_id,
    delivery_date,
    invoice_number
  )
  values (
    p_supplier_id,
    p_delivery_date,
    p_invoice_number
  )
  returning delivery_id into v_delivery_id;

  for v_item in
    select value
    from jsonb_array_elements(p_items)
  loop
    if not (v_item ? 'product_id')
      or not (v_item ? 'quantity')
      or not (v_item ? 'supply_price') then
      raise exception 'Each supply item must contain product_id, quantity and supply_price';
    end if;

    v_product_id := (v_item ->> 'product_id')::integer;
    v_quantity := (v_item ->> 'quantity')::integer;
    v_supply_price := (v_item ->> 'supply_price')::numeric;

    if v_quantity <= 0 then
      raise exception 'Supply item quantity must be greater than 0';
    end if;

    if v_supply_price <= 0 then
      raise exception 'Supply price must be greater than 0';
    end if;

    perform 1
    from public.products
    where product_id = v_product_id
    for update;

    if not found then
      raise exception 'Product with ID % does not exist', v_product_id;
    end if;

    insert into public.supply_item (
      delivery_id,
      product_id,
      quantity,
      supply_price
    )
    values (
      v_delivery_id,
      v_product_id,
      v_quantity,
      v_supply_price
    );

    update public.products
    set stock_quantity = stock_quantity + v_quantity
    where product_id = v_product_id;
  end loop;

  return v_delivery_id;
end;
$function$;

CREATE OR REPLACE PROCEDURE public.pr_register_payment(IN p_order_id integer, IN p_payment_date date, IN p_payment_method character varying)
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $procedure$
declare
  v_total_amount numeric(12, 2);
begin
  select o.total_amount
  into v_total_amount
  from public.orders as o
  where o.order_id = p_order_id;

  if not found then
    raise exception 'Order with ID % does not exist', p_order_id;
  end if;

  if p_payment_date > current_date then
    raise exception 'Payment date cannot be later than current date';
  end if;

  if exists (
    select 1
    from public.payments as p
    where p.order_id = p_order_id
  ) then
    raise exception 'Payment for order ID % already exists', p_order_id;
  end if;

  insert into public.payments (
    order_id,
    payment_date,
    amount,
    payment_method,
    status
  )
  values (
    p_order_id,
    p_payment_date,
    v_total_amount,
    p_payment_method,
    'Paid'
  );

  update public.orders
  set status = 'Paid'
  where order_id = p_order_id;
end;
$procedure$;

-- ========== Triggers ==========

CREATE TRIGGER trg_categories_bi BEFORE INSERT ON categories FOR EACH ROW EXECUTE FUNCTION fn_set_categories_id();
CREATE TRIGGER trg_customers_bi BEFORE INSERT ON customers FOR EACH ROW EXECUTE FUNCTION fn_set_customers_id();
CREATE TRIGGER trg_deliveries_bi BEFORE INSERT ON deliveries FOR EACH ROW EXECUTE FUNCTION fn_set_deliveries_id();
CREATE TRIGGER trg_order_items_bi BEFORE INSERT ON order_items FOR EACH ROW EXECUTE FUNCTION fn_set_order_items_id();
CREATE TRIGGER trg_orders_bi BEFORE INSERT ON orders FOR EACH ROW EXECUTE FUNCTION fn_set_orders_id();
CREATE TRIGGER trg_payments_bi BEFORE INSERT ON payments FOR EACH ROW EXECUTE FUNCTION fn_set_payments_id();
CREATE TRIGGER trg_products_bi BEFORE INSERT ON products FOR EACH ROW EXECUTE FUNCTION fn_set_products_id();
CREATE TRIGGER trg_shipment_bi BEFORE INSERT ON shipment FOR EACH ROW EXECUTE FUNCTION fn_set_shipment_id();
CREATE TRIGGER trg_suppliers_bi BEFORE INSERT ON suppliers FOR EACH ROW EXECUTE FUNCTION fn_set_suppliers_id();
CREATE TRIGGER trg_supply_item_bi BEFORE INSERT ON supply_item FOR EACH ROW EXECUTE FUNCTION fn_set_supply_item_id();

commit;
