// ========== Seed Data ==========
export const productSeed = [
  {
    category: 'smartphones',
    name: 'iPhone 15',
    price: 44999,
    stock: 8,
    discount: 5,
    description: 'Смартфон Apple з OLED-дисплеєм та якісною камерою.',
  },
  {
    category: 'smartphones',
    name: 'Samsung Galaxy S24',
    price: 38999,
    stock: 10,
    discount: 7,
    description: 'Флагманський смартфон Samsung для фото та продуктивності.',
  },
  {
    category: 'smartphones',
    name: 'Google Pixel 8',
    price: 32999,
    stock: 4,
    discount: 0,
    description: 'Смартфон Pixel з чистим Android та якісною обробкою фото.',
  },
  {
    category: 'smartphones',
    name: 'Xiaomi 14',
    price: 29999,
    stock: 0,
    discount: 10,
    description: 'Потужний смартфон із швидкою зарядкою та компактним корпусом.',
  },
  {
    category: 'smartphones',
    name: 'Nothing Phone (2a)',
    price: 19999,
    stock: 3,
    discount: 5,
    description: 'Смартфон із впізнаваним дизайном та плавною роботою.',
  },

  {
    category: 'notebooks',
    name: 'MacBook Air M2',
    price: 52999,
    stock: 6,
    discount: 4,
    description: 'Легкий ноутбук для роботи, навчання та поїздок.',
  },
  {
    category: 'notebooks',
    name: 'Lenovo ThinkPad E14 Gen 5',
    price: 36999,
    stock: 7,
    discount: 8,
    description: 'Надійний бізнес-ноутбук з зручною клавіатурою.',
  },
  {
    category: 'notebooks',
    name: 'ASUS Zenbook 14 OLED',
    price: 41999,
    stock: 5,
    discount: 6,
    description: 'Ноутбук з OLED-екраном для контенту та офісних задач.',
  },
  {
    category: 'notebooks',
    name: 'Acer Swift Go 14',
    price: 30999,
    stock: 2,
    discount: 0,
    description: 'Компактний ультрабук для щоденної мобільної роботи.',
  },
  {
    category: 'notebooks',
    name: 'Dell XPS 13',
    price: 58999,
    stock: 1,
    discount: 9,
    description: 'Преміальний ноутбук із компактним форм-фактором.',
  },

  {
    category: 'tablets',
    name: 'iPad Air 11',
    price: 31999,
    stock: 4,
    discount: 3,
    description: 'Планшет Apple для навчання, ескізів та роботи в дорозі.',
  },
  {
    category: 'tablets',
    name: 'Samsung Galaxy Tab S9 FE',
    price: 22999,
    stock: 6,
    discount: 5,
    description: 'Планшет з підтримкою стилуса для роботи та навчання.',
  },
  {
    category: 'tablets',
    name: 'Lenovo Tab P12',
    price: 18999,
    stock: 0,
    discount: 12,
    description: 'Планшет з великим екраном для мультимедіа.',
  },

  {
    category: 'accessories',
    name: 'Anker 65W USB-C Charger',
    price: 1799,
    stock: 25,
    discount: 0,
    description: 'Компактний зарядний пристрій на 65W для ноутбуків і смартфонів.',
  },
  {
    category: 'accessories',
    name: 'Logitech MX Master 3S',
    price: 4699,
    stock: 9,
    discount: 10,
    description: 'Зручна бездротова миша для офісної та креативної роботи.',
  },
  {
    category: 'accessories',
    name: 'Apple MagSafe Charger',
    price: 2199,
    stock: 11,
    discount: 0,
    description: 'Бездротовий зарядний пристрій для iPhone з MagSafe.',
  },
  {
    category: 'accessories',
    name: 'UGREEN USB-C Hub 6-in-1',
    price: 2499,
    stock: 7,
    discount: 6,
    description: 'USB-C хаб для підключення монітора, флешок та мережі.',
  },

  {
    category: 'audio',
    name: 'AirPods Pro 2',
    price: 10999,
    stock: 8,
    discount: 5,
    description: 'Бездротові навушники з активним шумозаглушенням.',
  },
  {
    category: 'audio',
    name: 'Sony WH-1000XM5',
    price: 14999,
    stock: 5,
    discount: 7,
    description: 'Повнорозмірні навушники преміум-класу для роботи та подорожей.',
  },
  {
    category: 'audio',
    name: 'JBL Charge 5',
    price: 6999,
    stock: 12,
    discount: 0,
    description: 'Портативна колонка з насиченим звучанням та захистом від води.',
  },
  {
    category: 'audio',
    name: 'Marshall Emberton II',
    price: 7999,
    stock: 2,
    discount: 4,
    description: 'Компактна Bluetooth-колонка у фірмовому стилі Marshall.',
  },

  {
    category: 'home',
    name: 'Philips Airfryer HD9252',
    price: 5999,
    stock: 10,
    discount: 8,
    description: 'Аерофритюрниця для щоденного приготування страв.',
  },
  {
    category: 'home',
    name: 'Tefal OptiGrill+',
    price: 9499,
    stock: 4,
    discount: 5,
    description: 'Електрогриль з автоматичними програмами приготування.',
  },
  {
    category: 'home',
    name: 'Xiaomi Mi Smart Kettle Pro',
    price: 2499,
    stock: 0,
    discount: 0,
    description: 'Розумний електрочайник з контролем температури.',
  },

  {
    category: 'monitors',
    name: 'LG UltraFine 27UP650',
    price: 13999,
    stock: 6,
    discount: 6,
    description: '4K-монітор для офісу та обробки контенту.',
  },
  {
    category: 'monitors',
    name: 'Dell S2722QC',
    price: 14999,
    stock: 3,
    discount: 5,
    description: 'Універсальний 27-дюймовий монітор з USB-C.',
  },
  {
    category: 'monitors',
    name: 'Samsung Odyssey G5 27',
    price: 11999,
    stock: 5,
    discount: 9,
    description: 'Ігровий монітор із високою частотою оновлення.',
  },

  {
    category: 'network',
    name: 'TP-Link Archer AX55',
    price: 3699,
    stock: 14,
    discount: 0,
    description: 'Wi-Fi 6 роутер для дому та невеликого офісу.',
  },
  {
    category: 'network',
    name: 'ASUS RT-AX58U',
    price: 4899,
    stock: 6,
    discount: 7,
    description: 'Надійний роутер із підтримкою Wi-Fi 6 і гостьових мереж.',
  },
  {
    category: 'network',
    name: 'Ubiquiti UniFi U6+',
    price: 6299,
    stock: 4,
    discount: 3,
    description: 'Точка доступу для стабільного покриття Wi-Fi у приміщенні.',
  },
  {
    category: 'network',
    name: 'MikroTik hAP ax3',
    price: 5499,
    stock: 2,
    discount: 0,
    description: 'Потужний маршрутизатор із гнучким налаштуванням мережі.',
  },
];
